"""PyGUIzer - Automatic Web GUI Generator for Python Functions"""

__version__ = "0.1.0"


class PyGUIzer:
    """Decorator for generating web GUI from Python functions."""

    # Class variable to track all decorated functions
    registered_functions = []

    def __init__(self, layout=None):
        self.layout = layout or {"sections": [{"name": "Main", "widgets": []}]}
        # Store registered functions for this instance
        self.functions = []

    def __call__(self, func):
        self.func = func
        # Store a reference to this PyGUIzer instance on the function
        func.__pyguizer__ = self
        # Add to registered functions list if not already present
        if func not in PyGUIzer.registered_functions:
            PyGUIzer.registered_functions.append(func)
        if func not in self.functions:
            self.functions.append(func)
        return func

    def register_function(self, func, group="default"):
        """Register a function with this PyGUIzer instance.

        Args:
            func: The function to register
            group: Optional group/category for the function
        """
        # Store a reference to this PyGUIzer instance on the function
        func.__pyguizer__ = self
        # Store group information on the function
        func.__pyguizer_group__ = group
        # Add to registered functions list if not already present
        if func not in PyGUIzer.registered_functions:
            PyGUIzer.registered_functions.append(func)
        if func not in self.functions:
            self.functions.append(func)

    @classmethod
    def run(
        cls,
        host="0.0.0.0",
        port=8000,
        title="PyGUIzer App",
        description="Multi-function PyGUIzer Application",
    ):
        """
        Run the PyGUIzer application with all registered functions.

        Args:
            host: Host to run the server on
            port: Port to run the server on
            title: Application title
        """
        import uvicorn

        from pyguizer.api.app import PyGUIzerApp
        from pyguizer.api.app import create_app as create_fastapi_app

        # Create PyGUIzerApp instance
        pyguizer_app = PyGUIzerApp(name=title, description=description)

        # Register all decorated functions
        for func in cls.registered_functions:
            # Get the PyGUIzer instance from the function
            pyguizer_instance = getattr(func, "__pyguizer__", None)
            # Get the group from the function
            group = getattr(func, "__pyguizer_group__", "default")
            # Register the function with its layout and group
            pyguizer_app.register_function(
                func, pyguizer_instance.layout if pyguizer_instance else None, group
            )

        # Create FastAPI app with the pre-configured PyGUIzerApp instance
        app = create_fastapi_app(pyguizer_app=pyguizer_app)

        # Update the FastAPI app title and description
        app.title = title
        app.description = (
            f"Multi-function web application generated by PyGUIzer "
            f"with {len(cls.registered_functions)} functions"
        )

        # Run the server
        print("=== PyGUIzer Application ===")
        print(f"Running {len(cls.registered_functions)} registered functions:")
        for func in cls.registered_functions:
            print(f"  - {func.__name__}")
        print(f"\nServer starting on http://{host}:{port}...")
        print(f"API documentation available at http://{host}:{port}/docs")
        print("\nPress Ctrl+C to stop the server")
        uvicorn.run(app, host=host, port=port)


# Lazy import core components to avoid circular dependencies and heavy imports


def __getattr__(name):
    """Lazy import for core components."""
    if name == "introspect_function":
        from pyguizer.core.introspection import introspect_function

        return introspect_function
    elif name == "generate_wso":
        from pyguizer.core.widget import generate_wso

        return generate_wso
    elif name == "create_app":
        from pyguizer.api.app import create_app

        return create_app
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


# Export main components
export = {
    "PyGUIzer": PyGUIzer,
}
