from typing import List, Optional, Dict, Set, Tuple
import uvicorn
from pyguizer import PyGUIzer
from pyguizer.api.app import create_app
from pathlib import Path
from enum import Enum
from datetime import datetime, date, time
from uuid import UUID
from decimal import Decimal

# Define an enum for testing
class Color(Enum):
    RED = "red"
    GREEN = "green"
    BLUE = "blue"

@PyGUIzer()
def advanced_profile(
    name: str = "World",
    age: int = 30,
    height: float = 1.75,
    is_active: bool = True,
    score: Decimal = Decimal("99.5"),
    user_id: UUID = UUID("12345678-1234-5678-1234-567812345678"),
    colors: List[str] = None,
    unique_colors: Set[str] = None,
    dimensions: Tuple[int, int, int] = (10, 20, 30),
    metadata: Dict[str, str] = None,
    profile_picture: Path = None,
    birth_date: date = None,
    birth_time: time = None,
    last_login: datetime = None,
    favorite_color: Color = Color.RED
) -> Dict[str, any]:
    """
    Generate an advanced user profile with various data types.
    
    Args:
        name: Your full name
        age: Your age in years
        height: Your height in meters
        is_active: Whether you're currently active
        score: Your performance score (decimal precision)
        user_id: Your unique identifier (UUID format)
        colors: List of favorite colors
        unique_colors: Set of unique favorite colors
        dimensions: Dimensions (width, height, depth)
        metadata: Additional key-value metadata
        profile_picture: Path to your profile picture
        birth_date: Your birth date
        birth_time: Your birth time
        last_login: Your last login datetime
        favorite_color: Your favorite color from predefined options
    
    Returns:
        A comprehensive user profile dictionary
    """
    if colors is None:
        colors = ["red", "green", "blue"]
    if unique_colors is None:
        unique_colors = {"red", "green"}
    if metadata is None:
        metadata = {"key": "value"}
    
    return {
        "message": f"Hello, {name}! Your profile has been created.",
        "age": age,
        "height": height,
        "is_active": is_active,
        "score": str(score),
        "user_id": str(user_id),
        "colors": colors,
        "unique_colors": list(unique_colors),
        "dimensions": dimensions,
        "metadata": metadata,
        "profile_picture": str(profile_picture) if profile_picture else None,
        "birth_date": str(birth_date) if birth_date else None,
        "birth_time": str(birth_time) if birth_time else None,
        "last_login": str(last_login) if last_login else None,
        "favorite_color": favorite_color.value
    }

@PyGUIzer()
def calculate_discount(price: float, discount_percentage: float, is_vip: bool = False) -> float:
    """Calculate the final price after applying discounts."""
    base_discount = price * (discount_percentage / 100)
    vip_bonus = price * 0.05 if is_vip else 0
    total_discount = base_discount + vip_bonus
    final_price = price - total_discount
    return round(final_price, 2)

@PyGUIzer()
def generate_markdown_report(
    title: str = "Sample Report",
    include_header: bool = True,
    include_list: bool = True,
    include_table: bool = True,
    include_code: bool = True,
    include_quotes: bool = True
) -> str:
    """
    Generate a markdown report with various formatting examples.
    
    Args:
        title: Report title
        include_header: Include header section
        include_list: Include list section
        include_table: Include table section
        include_code: Include code section
        include_quotes: Include quotes section
    
    Returns:
        A formatted markdown report
    """
    report = []
    
    if include_header:
        report.extend([
            f"# {title}",
            "",
            "This is a sample markdown report generated by PyGUIzer.",
            "",
            "## Introduction",
            "",
            "This report demonstrates various markdown formatting features:",
            "",
        ])
    
    if include_list:
        report.extend([
            "## List Features",
            "",
            "### Unordered List",
            "- Item 1",
            "- Item 2",
            "  - Subitem 2.1",
            "  - Subitem 2.2",
            "- Item 3",
            "",
            "### Ordered List",
            "1. First item",
            "2. Second item",
            "3. Third item",
            "",
        ])
    
    if include_table:
        report.extend([
            "## Table Features",
            "",
            "| Feature | Description | Status |",
            "|---------|-------------|--------|",
            "| Headers | H1, H2, H3 | ✅ |",
            "| Lists | Ordered, Unordered | ✅ |",
            "| Tables | Formatted data | ✅ |",
            "| Code | Inline & Blocks | ✅ |",
            "| Quotes | Blockquotes | ✅ |",
            "| Links | External URLs | ✅ |",
            "",
        ])
    
    if include_code:
        report.extend([
            "## Code Features",
            "",
            "### Inline Code",
            "Use `inline_code()` function for quick execution.",
            "",
            "### Code Block",
            "```python",
            "def hello_world(name: str) -> str:",
            "    return f\"Hello, {name}!\"",
            "",
            "# Example usage",
            "result = hello_world(\"PyGUIzer\")",
            "print(result)",
            "```",
            "",
            "### JSON Example",
            "```json",
            "{",
            "  \"name\": \"PyGUIzer\",",
            "  \"version\": \"1.0.0\",",
            "  \"features\": [\"markdown\", \"widgets\", \"real-time\"],",
            "  \"active\": true",
            "}",
            "```",
            "",
        ])
    
    if include_quotes:
        report.extend([
            "## Quote Features",
            "",
            "> This is a blockquote example.",
            "> ",
            "> - Markdown is lightweight and easy to read",
            "> - It converts to HTML seamlessly",
            "> - Perfect for documentation and reports",
            "",
        ])
    
    # Add a conclusion section
    report.extend([
        "## Conclusion",
        "",
        "This demonstrates the **markdown rendering capabilities** of PyGUIzer.",
        "",
        "Learn more about [PyGUIzer](https://github.com/pyguizer/pyguizer)",
        ""
    ])
    
    return "\n".join(report)

# Run the application if this file is executed directly
if __name__ == "__main__":
    # Create the FastAPI app using the generate_markdown_report function to test markdown rendering
    app = create_app(generate_markdown_report)
    
    # Run the server
    uvicorn.run(app, host="0.0.0.0", port=8003)

