"""FastAPI Application for PyGUIzer"""

from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field
from typing import Any, Dict, List, Optional
from pyguizer.core.introspection import introspect_function
from pyguizer.core.widget import generate_wso
from pyguizer.core.layout import process_layout


class RunRequest(BaseModel):
    """Request model for running a function."""
    inputs: Dict[str, Any] = Field(...)


class RunResponse(BaseModel):
    """Response model for function execution."""
    result: Any = Field(...)
    execution_time: float = Field(...)


class AppSpec(BaseModel):
    """Application specification model."""
    name: str = Field(...)
    description: str = Field(...) 
    layout: Dict[str, Any] = Field(...)


class PyGUIzerApp:
    """Main PyGUIzer application class."""
    
    def __init__(self, func, layout=None):
        self.func = func
        self.layout = layout or {"sections": [{"name": "Main", "widgets": []}]}
        
        # Introspect the function
        self.func_info = introspect_function(func)
        
        # Generate WSOs
        self.wsos = generate_wso(self.func_info["parameters"])
        
        # Process layout
        self.ui_layout = process_layout(self.wsos, self.layout)
    
    def get_app_spec(self) -> Dict[str, Any]:
        """Get the application specification."""
        return {
            "name": self.func_info["name"],
            "description": self.func_info["docstring"],
            "layout": self.ui_layout
        }
    
    def run_function(self, inputs: Dict[str, Any]) -> Any:
        """Run the function with provided inputs."""
        try:
            return self.func(**inputs)
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))


def create_app(func, layout=None):
    """Create a FastAPI app for the given function."""
    app = FastAPI(title="PyGUIzer App", description="Generated by PyGUIzer")
    pyguizer_app = PyGUIzerApp(func, layout)
    
    # Define API routes first (order matters!)
    @app.get("/api/spec")
    async def get_spec():
        """Get the application specification."""
        return pyguizer_app.get_app_spec()
    
    @app.post("/api/run", response_model=RunResponse)
    async def run(request: RunRequest):
        """Run the function with provided inputs."""
        import time
        start_time = time.time()
        result = pyguizer_app.run_function(request.inputs)
        execution_time = time.time() - start_time
        return RunResponse(result=result, execution_time=execution_time)
    
    # Mount static files for frontend - should come after API routes
    # This way, API requests are routed to the API endpoints, not the static files
    app.mount("/", StaticFiles(directory="frontend/build", html=True), name="static")
    
    return app
