"""FastAPI Application for PyGUIzer"""

import asyncio
import time
from typing import Any, Dict

from fastapi import Body, Depends, FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles

# Import dependency injection functions
from pyguizer.api.dependencies import get_pyguizer_app, get_task_manager
from pyguizer.api.endpoints import api_router
from pyguizer.api.examples import BATCH_EXAMPLES, RUN_EXAMPLES
from pyguizer.api.models import (
    BatchRequest,
    BatchResponse,
    RunRequest,
    RunResponse,
)
from pyguizer.api.services.pyguizer_app import PyGUIzerApp
from pyguizer.api.services.task_manager import TaskManager


async def execute_task(
    pyguizer_app: PyGUIzerApp,
    task_manager: TaskManager,
    task_id: str,
    func_name: str,
    inputs: Dict[str, Any],
):
    """Execute a task asynchronously with progress updates."""
    try:
        # Update task status to running
        task_manager.update_task(
            task_id,
            status="running",
            started_at=time.time(),
            progress=0.0,
            message="Task started",
        )

        # Simulate progress updates
        for i in range(0, 100, 20):
            task_manager.update_task(
                task_id, progress=i / 100, message=f"Processing... {i}%"
            )
            await asyncio.sleep(0)

            # Check if task was cancelled
            task = task_manager.get_task(task_id)
            if task["cancelled"]:
                return

        # Run the actual function
        result = await pyguizer_app.run_function(func_name, inputs)

        # Update task status to success
        task_manager.update_task(
            task_id,
            status="success",
            completed_at=time.time(),
            progress=1.0,
            message="Task completed successfully",
            result=result,
        )

    except Exception as e:
        # Update task status to failed
        task_manager.update_task(
            task_id,
            status="failed",
            completed_at=time.time(),
            error=str(e),
            message="Task failed",
        )


def create_app(pyguizer_app=None, func=None, layout=None):
    """Create a FastAPI app for the given function(s)."""
    app = FastAPI(title="PyGUIzer App", description="Generated by PyGUIzer")
    # Use provided pyguizer_app instance or create a new one
    # If pyguizer_app is a function (not a PyGUIzerApp instance), treat it as func
    if (
        pyguizer_app is not None
        and not isinstance(pyguizer_app, PyGUIzerApp)
        and callable(pyguizer_app)
    ):
        # First positional arg is a function, shift parameters
        if func is None:
            # create_app(func) -> func is in pyguizer_app position
            func = pyguizer_app
            pyguizer_app = None
        elif layout is None:
            # create_app(func, layout) -> func is in pyguizer_app, layout is in func
            actual_func = pyguizer_app
            actual_layout = func
            func = actual_func
            layout = actual_layout
            pyguizer_app = None

    if pyguizer_app is None:
        pyguizer_app = PyGUIzerApp(func=func, layout=layout)
    task_manager = TaskManager()

    # Dependency injection setup
    app.dependency_overrides[get_pyguizer_app] = lambda: pyguizer_app
    app.dependency_overrides[get_task_manager] = lambda: task_manager

    # Define API routes first (order matters!)
    @app.get("/api/spec")
    async def get_spec():
        """Get the application specification."""
        import json
        import logging

        logger = logging.getLogger(__name__)
        try:
            spec = pyguizer_app.get_app_spec()
            # Create a copy of the spec to avoid modifying the original
            spec_copy = json.loads(json.dumps(spec, default=str))
            logger.info(
                "Successfully generated spec with %d functions",
                len(spec_copy.get('functions', []))
            )
            return spec_copy
        except Exception as e:
            logger.error(f"Error generating spec: {str(e)}", exc_info=True)
            raise HTTPException(
                status_code=500, detail=f"Failed to generate spec: {str(e)}"
            )

    @app.post("/api/shutdown")
    async def shutdown():
        """Shutdown the server."""
        import logging
        import os
        import signal

        logger = logging.getLogger(__name__)
        logger.info("Shutdown requested")
        # For Windows, we'll use a different approach since os.kill with signal.SIGTERM
        # doesn't work the same
        if os.name == "nt":  # Windows
            import subprocess

            subprocess.Popen("taskkill /F /PID {}".format(os.getpid()), shell=True)
        else:  # Unix-like
            os.kill(os.getpid(), signal.SIGTERM)
        return {"status": "shutting down"}

    @app.post("/api/run", response_model=RunResponse)
    async def run(request: RunRequest = Body(..., openapi_examples=RUN_EXAMPLES)):
        """Run a function with provided inputs."""
        # Validate function exists before creating task
        if request.func_name not in pyguizer_app.function_registry:
            raise HTTPException(
                status_code=404, detail=f"Function '{request.func_name}' not found"
            )

        # Create a new task
        task_id = task_manager.create_task()

        # Start task execution in the background
        asyncio.create_task(
            execute_task(
                pyguizer_app, task_manager, task_id, request.func_name, request.inputs
            )
        )

        return RunResponse(task_id=task_id, status="pending")

    @app.post("/api/batch", response_model=BatchResponse)
    async def run_batch(
        request: BatchRequest = Body(..., openapi_examples=BATCH_EXAMPLES)
    ):
        """Run multiple functions in batch."""
        try:
            functions = request.functions
            if not functions:
                raise HTTPException(
                    status_code=400, detail="No functions provided for batch processing"
                )

            # Create a batch task
            batch_task_id = task_manager.create_task()
            task_manager.update_task(
                batch_task_id,
                status="running",
                started_at=time.time(),
                progress=0.0,
                message=f"Starting batch processing of {len(functions)} functions",
            )

            # Process functions concurrently
            results = []
            total_functions = len(functions)

            # Create tasks for each function
            async def process_function(i, func_data):
                func_name = func_data.name
                inputs = func_data.inputs

                try:
                    # Run the function
                    result = await pyguizer_app.run_function(func_name, inputs)
                    return i, {"function": func_name, "result": result}
                except Exception as e:
                    return i, {"function": func_name, "error": str(e)}

            # Create and run all tasks concurrently
            tasks = [
                process_function(i, func_data) for i, func_data in enumerate(functions)
            ]
            function_results = await asyncio.gather(*tasks)

            # Sort results by original order
            function_results.sort(key=lambda x: x[0])
            results = [result for _, result in function_results]

            # Update batch progress to complete
            task_manager.update_task(
                batch_task_id,
                progress=1.0,
                message=f"Processed all {total_functions} functions concurrently",
            )

            # Update batch task status
            task_manager.update_task(
                batch_task_id,
                status="success",
                completed_at=time.time(),
                progress=1.0,
                message=f"Batch processing completed: {total_functions} functions",
                result=results,
            )

            return BatchResponse(batch_id=batch_task_id, status="success")
        except Exception as e:
            # Handle batch processing error
            if "batch_task_id" in locals():
                task_manager.update_task(
                    batch_task_id,
                    status="failed",
                    completed_at=time.time(),
                    error=str(e),
                    message="Batch processing failed",
                )
            raise HTTPException(status_code=500, detail=str(e))

    # Include all other API endpoints from the endpoints module
    app.include_router(
        api_router, dependencies=[Depends(get_pyguizer_app), Depends(get_task_manager)]
    )

    # Mount static files for frontend - should come after API routes
    # This way, API requests are routed to the API endpoints, not the static files
    try:
        # Try to mount static files
        import os

        static_dir = os.path.join(
            os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
            "frontend",
            "build",
        )
        if os.path.exists(static_dir):
            app.mount("/", StaticFiles(directory=static_dir, html=True), name="static")
        else:
            # If frontend build directory doesn't exist, create a simple fallback
            from fastapi.responses import HTMLResponse

            @app.get("/")
            async def root():
                return HTMLResponse("""
                    <html>
                        <head>
                            <title>PyGUIzer</title>
                        </head>
                        <body>
                            <h1>PyGUIzer Backend Running</h1>
                            <p>Frontend build directory not found.</p>
                            <p>Please build the frontend or check the installation.</p>
                        </body>
                    </html>
                    """)

    except Exception as e:
        print(f"Error mounting static files: {e}")
        # Create a simple fallback
        from fastapi.responses import HTMLResponse

        @app.get("/")
        async def root():
            return HTMLResponse("""
                <html>
                    <head>
                        <title>PyGUIzer</title>
                    </head>
                    <body>
                        <h1>PyGUIzer Backend Running</h1>
                        <p>Static files not available.</p>
                    </body>
                </html>
                """)

    return app


# Main entry point
if __name__ == "__main__":
    import uvicorn

    app = create_app()
    uvicorn.run(app, host="0.0.0.0", port=8000)
